<?php

namespace App\Console\Commands;

use App\Models\StockTransaction;
use Illuminate\Console\Command;

class ClearAutoGeneratedNotes extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'notes:clear-auto-generated';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Clear auto-generated "Imported from Webull CSV" notes from stock transactions';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        $this->info('Clearing auto-generated notes...');

        $count = StockTransaction::where('notes', 'Imported from Webull CSV')
            ->update(['notes' => null]);

        $this->info("Cleared {$count} auto-generated notes from stock transactions.");
        $this->info('Notes fields are now ready for user input.');
    }
}
