<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('trade_alerts', function (Blueprint $table) {
            $table->boolean('is_paper')->default(false)->after('pipeline_run')->comment('True if generated by paper trading instance');
            $table->index('is_paper');
        });
    }

    public function down(): void
    {
        Schema::table('trade_alerts', function (Blueprint $table) {
            $table->dropIndex(['is_paper']);
            $table->dropColumn('is_paper');
        });
    }
};
